# Generated by Django 4.2.1 on 2023-06-04 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='date_posted',
        ),
    ]
